platform :ios, '9.0'

target 'Chalmers Card' do
  use_frameworks!

  pod 'UIColor-Hex-Swift'
  pod 'UICountingLabel'
  pod 'CWStatusBarNotification', '~> 2.3.4'
  pod 'UINavigationBar+Addition'
  pod 'Eureka', '~> 1.7'
  pod 'KeychainSwift', '~> 3.0'
  pod 'Alamofire', '~> 3.4'
  pod 'NSDate+TimeAgo'
end
